In [1]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv("C:/Users/sharan/Desktop/Boston.csv")

In [6]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  CAT. MEDV  Unnamed: 15  Unnamed: 16  
0  396.90   4.98  24.0          0          NaN          NaN  
1  396.90   9.14  21.6          0          NaN          NaN  
2  392.83   4.03  34.7          1          NaN          NaN  
3  394.63   2.94  33.4          1          NaN          NaN  
4  396.90   5.33  36.2          1          NaN          NaN

In [7]:
df.drop(["Unnamed: 15", "Unnamed: 16"], axis=1,inplace=True)

In [8]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  CAT. MEDV  
0  396.90   4.98  24.0          0  
1  396.90   9.14  21.6          0  
2  392.83   4.03  34.7          1  
3  394.63   2.94  33.4          1  
4  396.90   5.33  36.2          1

In [10]:
y=df["CAT. MEDV"]
x=df["RM"]

In [11]:
y

0      0
1      0
2      1
3      1
4      1
      ..
501    0
502    0
503    0
504    0
505    0
Name: CAT. MEDV, Length: 506, dtype: int64

In [12]:
y=pd.DataFrame(y)
x=pd.DataFrame(x)

In [13]:
y

CAT. MEDV
0            0
1            0
2            1
3            1
4            1
..         ...
501          0
502          0
503          0
504          0
505          0

[506 rows x 1 columns]

In [14]:
from sklearn.model_selection import train_test_split


In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=5)

In [16]:
x_train

RM
445  6.459
428  6.193
481  6.750
55   7.249
488  5.454
..     ...
486  6.114
189  7.185
495  5.670
206  6.326
355  5.936

[354 rows x 1 columns]

In [17]:
from sklearn.tree import DecisionTreeClassifier


In [18]:
model=DecisionTreeClassifier()

In [19]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [20]:
y_pred=model.predict(x_test)

In [21]:
y_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

In [22]:
y_test

CAT. MEDV
226          1
292          0
90           0
373          0
273          1
..         ...
60           0
108          0
298          0
138          0
370          1

[152 rows x 1 columns]

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [24]:
confusion_matrix(y_test,y_pred)

array([[122,   5],
       [  7,  18]], dtype=int64)

In [26]:
accuracy_score(y_test,y_pred)

0.9210526315789473

In [27]:
new_data=[5]

In [28]:
m=pd.DataFrame(new_data)

In [29]:
m

0
0  5

In [30]:
model.predict(m)

C:\Users\sharan\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)