In [1]:
#numpy: It is a fundamental package for scientific computing using python. Main benefit of numpy is powerful n-dimensional
#array it provides. 
#Array is a collection of items.
#Numpy= numerical+python(for scientific computing)
#pandas= panel+data(for dataframe manipulation)

In [2]:
import numpy as np


In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
#generating numbers from 0 to 50 with an interval of 2
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [8]:
np.zeros(62)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
k=np.ones((6,5))
k

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
len(k)

6

In [19]:
k.reshape(5,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
np.random.rand(4,4)

array([[0.76118661, 0.31837526, 0.85333653, 0.8050697 ],
       [0.47679667, 0.80807482, 0.06081926, 0.32984881],
       [0.56001319, 0.17430683, 0.49316731, 0.66126513],
       [0.00517128, 0.79188687, 0.67446025, 0.1867925 ]])

In [24]:
np.random.randint(4,15,3)

array([6, 5, 6])

In [29]:
m=np.random.randint(4,100,10)
m

array([70, 13, 85, 84, 66, 45, 35, 44, 12, 34])

In [28]:
np.random.randint(4,60,(5,5))

array([[42, 32, 54, 32,  4],
       [14,  5, 16, 35,  6],
       [31, 29, 53, 35, 52],
       [59, 13, 41, 41, 16],
       [15,  6, 58, 33, 35]])

In [30]:
m[-1]

34

In [33]:
m[-5:]

array([45, 35, 44, 12, 34])

In [34]:
m[:-5]

array([70, 13, 85, 84, 66])

In [35]:
m[:]

array([70, 13, 85, 84, 66, 45, 35, 44, 12, 34])

In [37]:
m[2:7]

array([85, 84, 66, 45, 35])

In [39]:
#conditional indexing
m[m>50]

array([70, 85, 84, 66])

In [40]:
m[m>50]=60

In [41]:
m

array([60, 13, 60, 60, 60, 45, 35, 44, 12, 34])

In [42]:
n=m.copy()

In [43]:
n

array([60, 13, 60, 60, 60, 45, 35, 44, 12, 34])